import * as React from 'react';
import { Text, View, ScrollView } from 'react-native';
import { Avatar } from 'react-native-elements';
import Admob from '../../admob'

export default class App extends React.Component {

  render() {
    return (
      <View style={{ paddingLeft: 20, paddingRight: 20, backgroundColor: 'black', flex: 1 }}>
        <ScrollView>
          <View style={{ justifyContent: 'center', alignItems: 'center', paddingBottom: 20, paddingTop: 20, backgroundColor: 'black' }}>
            <Avatar
              size='xlarge'
              rounded
              source={{ uri: 'https://res.cloudinary.com/dib0twra5/image/upload/v1660089840/Livros/ab6761610000e5eb9f0c70d55c26e9773d00b7b1_qu5y6z.png' }} />
          </View>
          <View>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Maria Eugênia Pereira dos Santos era uma garotinha bonita quando conheceu Raul Varella Seixas. Ela tinha sete anos, e ele nove. O namoro, que durante anos ficou somente na troca de olhares e bilhetinhos, culminou no casamento dos dois, às 17:30h do dia 16 de setembro de 1944, na Igreja do Bonfim, em Salvador, na Bahia. Nove meses após a união de Raul e Maria Eugênia, nascia o primeiro filho do casal, Raul Santos Seixas, em 28 de junho de 1945.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>“Nasci baiano mesmo, na av. 7 de setembro, número 108, que é a avenida principal de Salvador. Hoje estão comendo bacalhau” …brincaria Raul, mais tarde, referindo-se ao Restaurante Português, que funciona hoje, na casa em que nasceu.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>A vasta biblioteca de seu pai era seu brinquedo favorito. E foi daí que veio o gosto pela palavra e a miopia precoce. Vivia trancado no quarto devorando o “Livro dos Porquês” do “Tesouro da Juventude”. Inventava histórias fantásticas que, transformadas em gibis, e com desenhos do próprio Raul, eram vendidos ao irmão caçula, Plininho (Plínio Santos Seixas, três anos mais novo). Melô era o personagem central de suas histórias, um cientista louco que viajava no tempo com figuras históricas, Deus e o Diabo.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>“Eu estava muito preocupado com a filosofia sem o saber (isto é, eu não sabia que era filosofia aquilo que eu pensava). Tinha mania de pensar que eu era maluco e ninguém queria me dizer. Gostava de ficar sozinho. Pensando. Horas e horas. Meu mundo interior é, e sempre foi, muito rico e intenso. Por isso o mundo exterior naquela época não me interessava muito. Eu criava o meu.”No ano de 1954, Raul ganhou seu primeiro violão, presente dos pais, ao qual, a princípio, ele não deu muita importância. Porém, pouco a pouco, foi dedilhando e, sozinho, aprendeu a tocar algumas músicas, acabando por se apaixonar pela novidade.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>A família Seixas mudou-se para uma casa que ficava próxima ao Consulado Americano. Ali Raul conheceu os garotos do consulado, que lhe emprestaram alguns discos de Elvis Presley, Little Richard, Fats Domino, Chuck Berry etc. Foi o primeiro contato com o Rock and Roll.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>“Eu ouvia os discos de Elvis Presley até estragar os sulcos. O rock era como uma chave que abriria minhas portas que viviam fechadas. Usava camisa vermelha, gola virada para cima. As mães não deixavam as filhinhas chegarem perto de mim porque eu era torto como o James Dean. Olhava de lado, com jeito de durão. Cada vez que eu cumprimentava uma pessoa dava três giros em torno do próprio corpo. Eu era o próprio rock. Eu era Elvis quando andava e penteava o topete. Eu era alvo de risos, gracinhas, claro. Eu tinha assumido uma maneira de vestir, falar e agir que ninguém conhecia. Claro que eu não tinha consciência da mudança social que o rock implicava. Eu achava que os jovens iam dominar o mundo.”</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Aos poucos a escola foi ficando de lado. O bom era ficar na loja Can-tinho da Música, curtindo rock and roll ou marcando ponto no Elvis Rock Club, fã-clube de Elvis Presley, fundado por Raulzito e o amigo Waldir Serrão. Corria o ano de 1962 e a necessidade de fazer rock levou Raul a fundar, ao lado dos irmãos Délcio e Thildo Gama, o grupo Os Relâm-pagos do Rock. Chegaram a se apresentar na TV Itapoan, onde foram chamados de cantores de “música de cowboy”.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>“Eu era um fracasso na escola. A escola não me dizia nada do que eu queria saber. Tudo o que eu sei, eu devo ao mundo, à rua, à vivência e, principalmente a mim mesmo. Repeti 5 vezes a 2. série do ginásio. Nunca aprendi nada na escola. Minto. Aprendi a odiá-la.”</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>O ano de 1964 foi importante para Raul Seixas. Os Relâmpagos do Rock, com nova formação, passam a se chamar The Panthers. Foi também o ano da profissionalização definitiva e da des-coberta dos Beatles.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Ainda em 1964, The Panthers entra em estúdio para gravar aquela que viria a ser a primeira gravação oficial: duas músicas para serem lançadas em um compacto (“Nanny”/ “Coração Partido”) pela Astor, que acabaram ficando apenas no acetato, não sendo lançadas comercialmente. Somente em 1992, a música “Nanny” seria lançada, entre outras gravações raras, no álbum O Baú do Raul.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>O grupo passou então a se chamar Raulzito e Os Panteras. Depois de comprar uma aparelhagem nova e melhor, passou a tocar em boates e em shows em que, muitas vezes, brilhavam astros da Jovem Guarda como Roberto Carlos, Wanderléa, Jerry Adriani e, Rosemary, entre outros. Seus maiores rivais são os grupos de samba e bossa nova, aquartelados no Teatro Vila Velha de um lado e do outro o Cinema Roma, que era o templo do rock and roll, organizado por Waldir Serrão, O Big Ben.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Em nome do namoro com a americana Edith Wisner, Raul resolve parar tudo e retomar os estudos e, em pouco tempo, prestar o vestibular (para passar num dos pr-meiros lugares) para a faculdade de Direito. “Eu queria provar às pessoas, à minha família, como era fácil isso de estudar, passar em exames. Como não tinha a mínima importância.” Tão sem importância que, em 1967, decide ao mesmo tempo casar com Edith e retomar a carreira com Os Panteras.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Atendendo a um pedido de Jerry Adriani, Raul, Edith e Os Panteras partiram em viagem para o Rio, realizando um velho sonho. Conseguiram gravar, para a Odeon, o LP Raulzito e Os Panteras. Lançado em 1968, o disco foi ignorado tanto pela crítica quanto pelo público.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>“Chegamos em fim de safra. Não entendíamos o que estava acontecendo. Agnaldo Timóteo de um lado, Gil e Os Mutantes de outro. Tocávamos coisas complicadas, minhas letras falavam de agnosticismo, essas coisas, e complicamos demais. Não tínhamos idéia do que era comercial em matéria de música em português.”</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Com o fracasso do disco, ficam algum tempo como banda de apoio de Jerry Adriani, até a dissolução do grupo. “Só sobrou eu. Os outros não agüentaram a barra e caíram fora”. Desiludido e psicologicamente abalado, Raul voltou para Salvador.”</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Em 1970, conheceu Evandro Ribeiro, diretor da CBS, hoje Sony Music. “Talvez eu tivesse trilhado o caminho da paranóia se não tivesse tido a chance que tive. Conheci o diretor da gravadora CBS lá mesmo, na Bahia, e foi ele mesmo quem me deu oportunidade de estar em contato com a arte outra vez.” E lá se foi Raul, com Edith, de volta para o Rio; desta vez para trabalhar como produtor de discos na CBS. Durante um ano, Raul criaria músicas e discos de sucesso para Jerry Adriani, Trio Ternura, Renato e Seus Blue Caps, Tony e Frankie, Diana e Sérgio Sampaio. “Sérgio Sampaio foi o primeiro artista que eu realmente descobri. Acreditei muito nesse cara. Acreditei tanto que ele me incentivou a ser artista outra vez.” Em novembro daquele ano, nasceu Simone, a primeira filha.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>O incentivo de Sérgio Sampaio levou Raul a produzir e lançar, em julho de 1971, aproveitando a viagem do presidente da CBS, o LP Sociedade da Grã-Ordem Kavernista – apresenta – Sessão das 10, com participações do próprio Raul, com Sérgio Sampaio, Miriam Batucada, Edy Star. Isso lhe valeu a expulsão da CBS quando o presidente voltou. O disco então sumiu, “misteriosamente”, do mercado.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>“Neste disco cada um cantava suas músicas em faixas separadas, num trabalho que resumia o caos da época. Valeu a pena, apesar de ter vendido muito pouco. Nós nos divertimos muito. Foi também a primeira vez que eu fiz algo para ser consumido e do qual me senti paranoicamente orgulhoso e feliz. Como os Beatles, que aprenderam no estúdio, eu aprendi tudo na CBS, os macetes todos. Aprendi a fazer música fácil, comercial, intuitiva e bonitinha, que leva direitinho o que a gente quer dizer.”</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Em setembro de 1972, no VII Festival Internacional da Canção, à frente de um público ávido por novidades, Raul, mais uma vez incentivado pelo amigo Sérgio Sampaio, resolveu se tornar “popular”. Inscreveu no festival as canções “Eu sou eu, Nicuri é o Diabo”, defendida por Lena Rios e Os Lobos, e “Let me Sing, Let me Sing”, mistura de rock com baião, interpretada pelo próprio Raul, travestido de Elvis. Ambas foram classificadas.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>“Depois de sair da CBS, onde ganhava 4 mil cruzeiros por mês, decidi ser Raul Seixas. Então usei, este é o termo, aquele negócio de brilhantina, do rock, do casaco de couro, como trampolim, como uma maneira de ser conhecido. Por que eu só passei a existir depois daquela encenação, daquele teatro que eu fiz. Combinar rock com baião foi a fórmula certa para chamar a atenção. Mas foi só o começo.”</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>A classificação de “Let me Sing, Let me Sing” entre as finalistas, além da excelente repercussão que Raul Seixas provocou no público e na imprensa, garantiu a continuidade de sua carreira como cantor e compositor da Philips. A consagração ainda tardaria alguns meses; tempo durante os quais Raul atuaria ao velho estilo, como produtor (e, no caso, também como cantor, anônimo, sem crédito na capa) de um disco antológico de clássicos de rock and roll e da Jovem Guarda: Os 24 Maiores Sucessos da Era do Rock (selo Polyfar, 1973).</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Em 1975, esse disco seria reeditado com algumas alterações, como o nome de Raul na capa e um novo título, 20 Anos de Rock, aproveitando a notoriedade de Raul. Mas o “buuum” só viria mesmo com a explosão do compacto ”Ouro de Tolo”, (curiosidade: teve que ser prensado duas vezes em uma semana!). ”Ouro de Tolo” tinha uma letra autobiográfica e ao mesmo tempo uma bofetada na face da classe média do país (que trocava a verdadeira realização pelo acesso às bugigangas comuns de consumo), naqueles tempos de Milagre Brasileiro.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Contratado pela Philips (gravadora onde brilhavam os medalhões da MPB como Caetano, Gil, Gal etc…), Raul Seixas partiu para o primeiro álbum solo, Krig-ha, Bandolo! O título refere-se ao grito de guerra de Tarzan, que quer dizer: “cuidado, aí vem o inimigo”. Lançado em 1973 é considerado pela crítica como um dos seus melhores trabalhos.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>“O LP Krig-ha, Bandolo! foi feito todo de uma vez. A música Ouro de Tolo foi lançada antes, por causa de uma jogada comercial da Philips, que remexeu na ópera, que é o LP, e dela retirou a parte que achava mais interessante. Então, para mim, o valor e o gosto ficam por conta de todo o LP, porque ele é o todo de um trabalho, onde todas as músicas se interligam e de onde é quase impossível você só tirar e citar uma parte.”</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Raul Seixas e Paulo Coelho lançam Sociedade Alternativa em agosto, e dedicam-se com afinco aos estudos esotéricos, mergulhando fundo na obra do mago inglês Aleister Crowley. Raul anunciava que era hora de mudar o mundo e distribuía nos shows um gibi/manifesto chamado “A Fundação de Krig-ha”, ilustrado por Adalgisa Rios (esposa de Paulo, na época). A Sociedade Alternativa, com sede alugada, papel timbrado e relatórios mensais, chegou a anunciar a aquisição de um terreno em Minas Gerais, para a construção da Cidade das Estrelas, uma comunidade onde a lei única era “Faze o que tu queres, há de ser tudo da lei.” A idéia da Sociedade Alternativa não agradou a muitos e Raul foi preso e torturado pelo DOPS, tendo que deixar o país. Raul, Paulo, Edith e Adalgisa decidiram partir para os Estados Unidos, onde fizeram contato com algumas personalidades.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Enquanto isso aqui no Brasil, a música “Gita” tocava de norte a sul do país. E foi graças a esse sucesso que Raul e Cia. voltaram para o Brasil. Foi nessa época que o casamento de Raul com Edith foi chegando ao fim, e ela decidiu voltar para os Estados Unidos, levando consigo a filha do casal. O sucesso de Gita deu a Raul Seixas o primeiro Disco de Ouro, com mais de 600 mil cópias vendidas. O mesmo não aconteceu com o disco seguinte: Novo Aeon (1975, Philips), que vendeu apenas 60 mil. “Foi a maior decepção, mas dei a volta por cima com Há 10 Mil Anos Atrás.”</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Raul conheceu, então, outra americana, Glória Vaquer (“Spacey Glow”), irmã de seu guitarrista Gay Vaquer. Casou-se com Glória e, desta união, nasceu, no Rio de Janeiro, a segunda filha de Raul, Scarlet, em junho de 1976. Nesse ano lançou o álbum Há 10 Mil Anos Atrás, com Raul maquiado na capa como um “sábio ancião”. Chegou então ao fim a parceria com Paulo Coelho, embora conti-nuassem amigos (ou inimigos íntimos).</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Decidiu sair da Philips para outra gravadora, a recém-fundada WEA. Marcou esse período o rosto sem barba nem bigode (suas “marcas registradas”) e a relação com um novo parceiro (e antigo vizinho dos tempos do Rio), Cláudio Roberto, professor de ginástica, poeta e cantor nas horas vagas. Juntos realizaram o LP O Dia em que a Terra Parou, em 1977. A crítica não gostou. Foi dito que não mantinha o mesmo “nível” dos trabalhos anteriores. Mas os fãs se deliciam com “Maluco Beleza”, “Sapato 36” e a faixa-título. Raul chegou a fazer alguns shows, mas sem muito sucesso, devido às críticas ao LP. Foi então que se separou de Glória, que, a exemplo de Edith, também voltou aos Estados Unidos com a filha Scarlet.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>As mudanças em sua vida pessoal e profissional somadas a problemas de saúde, abalaram Raul. Para recuperar-se da pancreatite, agravada pelo consumo de bebidas alcoólicas, Raul Seixas resolveu passar alguns meses na fazenda dos pais em Dias D’Avilla, interior da Bahia. Voltou de lá mais gordo e com uma nova companheira, Tânia Menna Barreto. Com ela dividiu parceria em seu novo álbum, Mata Virgem (1978, WEA). O disco trazia de volta Paulo Coelho, mas a má divugação atrapalhou a vendagem do LP e a crítica também não ajudou.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Em 1979 faz seu último álbum para a WEA, Por Quem os Sinos Dobram, em parceria com o amigo Oscar Rasmussen. Raul saiu da gravadora levando sua secretária de imprensa, a carioca Ângela Costa, hoje mais conhecida como Kika Seixas.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Raul assinou um novo contrato com uma velha conhecida sua, a CBS e, em 1980, lançou o álbum Abre-te, Sésamo. O disco vendeu razoavelmente, porém bem menos do que merecia. Raul e Kika decidiram morar em São Paulo e, com a ajuda de Jair Rodrigues, conseguiram alugar uma casa no bairro do Brooklin.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>São Paulo o recebeu de braços abertos. Iniciou, então, uma série de shows pela capital e interior do estado paulista. Na Zona Sul da cidade de São Paulo, nasceu, em 1981, a terceira e última filha de Raul, Vivian. Chegou a fazer uma temporada no Teatro Pixinguinha com sucesso absoluto.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Ainda em 81, Raul rescindiu o contrato com a CBS por pedirem que dedicasse o próximo disco a Lady Diana – ela era ”o assunto do momento”. Nessa época, Sylvio Passos, com 18 anos, comunicou a Raul Seixas que havia fundado o Raul Rock Club. Ele ficou surpreso, e passou a participar ativamente do que denominaria de Raul Seixas Oficial Fã-Clube. Sem gravadora, mas com um público enorme e fiel, apresentou-se para mais de 150 mil pessoas em 13 de fevereiro de 1982 no Festival Música na Praia, em Santos, São Paulo. Mas Raul andava insatisfeito e mergulhava cada vez mais na bebida, o que levou ao cancelamento de shows e crises de hepatite. Em maio de 82, apresentou-se tão alcoolizado em Caieiras, interior de São Paulo, que acabou sendo tomado por impostor de si mesmo, sendo preso e ameaçado pelo delegado da cidade.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Deprimido, sem um contrato com uma gravadora e ainda com problemas de saúde, Raul, juntamente com Kika, desenvolveu o projeto da ópera-rock Nuit e saiu batendo de porta em porta, visitando todas as gravadoras. Nada aconteceu. Chegou ao cúmulo de ouvir de um diretor artístico a seguinte frase: “Já estou vacinado contra Raul Seixas.” Magoado, Raul voltou para o Rio e ficou alguns meses num apartamento em Copacabana. Até que João Lara Mesquita, jovem diretor do Estúdio Eldorado e fã incondicional de Raul, resolveu realizar um antigo projeto e convidou o ídolo para gravar. Raul, Kika e a filha Vivian então retornaram para São Paulo, e, em abril de 1983, o músico lançou o álbum Raul Seixas. O disco trazia também uma faixa gravada, ao vivo, durante um show realizado no Sociedade Esportiva Palmeiras, onde Raul Seixas contou, através das músicas, a história do rock and roll para mais de 10 mil pessoas.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Em 1983, lançou o livro As Aventuras de Raul Seixas na Cidade de Thor, dividido em três partes: a primeira, um diário escrito entre os sete e os quatorze anos, no qual nota-se um grande conhecimento de rock and roll; na segunda parte, uma série de contos feitos entre os doze e os vinte e um anos; e, finalmente, na terceira, uma história em quadrinhos, chamada A Lei dos Assassinos da Montanha que, segundo Raul, era um bom exemplo de humor negro.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Com o sucesso do disco, do livro e da turnê pelo Brasil, Raul e Kika realizaram uma viagem aos Estados Unidos para acompanhar de perto o que estava acontecendo musicalmente por lá. Voltaram com a bagagem cheia e inspiradíssimos. Raul então assinou novo contrato, dessa vez com a Som Livre e, em junho de 1984, lançou o álbum Metrô Linha 743.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>O penúltimo casamento de Raul foi-se rompendo. A sua saúde também não andava boa. Mais uma vez ele decidiu voltar para Salvador, como fizera em 1978, para se recuperar. Depois de curta permanência em Salvador, voltou para São Paulo com nova companheira, Lena Coutinho.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Em São Paulo, junto com Lena, procurou uma nova gravadora, mas as portas do mundo artístico pareciam estar fechadas novamente para Raul. Enquanto isso, milhares de fãs e amigos permaneceram na expectativa de novidades. Em São Paulo, no ano de 1985, o Raul Rock Club (o Fã-Clube Oficial) lança o álbum Let me Sing my Rock and Roll, o primeiro disco produzido e distribuído independentemente por um fã-clube brasileiro, disputado hoje a peso de ouro por fãs e colecionadores.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Durante o ano de 1986, Raul e Lena continuaram à procura de uma gravadora e, finalmente, com a ajuda de amigos assinaram contrato para dois álbuns com a Copacabana. Porém, os problemas com a saúde atrapalharam as sessões de gravação no estúdio e o LP, que todos esperavam para esse ano, acabou sendo lançado só no início de 1987. O disco trazia como título o grito de guerra de rock and roll: Uah-Bap-Lu-Bap-Lah-Béin-Bum!</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>O disco tocou de norte a sul do país e mais uma vez, Raul Seixas era notícia, ocupando lugares de destaque na mídia e, o melhor, sua música estava na boca do povo. Contudo, continuava desaparecido dos palcos e da TV devido à sua saúde precária (em parte culpa do problema do abuso de bebidas alcoólicas).</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>A música “Cowboy Fora-da-Lei” estourou nas paradas de sucesso ganhando videoclipe no Fantástico e a sua inclusão na trilha sonora da novela das sete da Rede Globo. A música revelava uma “quase” paranóia de Raul, onde diz: “Mamãe, não quero ser prefeito/ pode ser que eu seja eleito/ e alguém pode querer me assassinar.”</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>A convite do discípulo e amigo Marcelo Nova, então vocalista e letrista do grupo baiano Camisa de Vênus, Raul Seixas participou da gravação do álbum que o grupo preparava para lançar, dividindo vocais e parceria com Marcelo Nova na música “Muita Estrela, Pouca Constelação”, referindo-se ao cenário pop brasileiro de maneira desdenhosa.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>No ano seguinte,1988, mostrou que ainda estava “vivo”, lançando, em setembro, o álbum A Pedra do Gênesis, que falava da controvertida Sociedade Alternativa.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>A música “Não Quero Mais Andar na Contramão”, provou que Raul não estava mais a fim de maluquices e que seu papo agora era paz e sossego, no aconchego do lar… sossego que virou tédio. Marcelo Nova, para tirá-lo desse tédio, convidou-o para viajar para Salvador, onde iria se apresentar.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Raul, que estava afastado dos palcos há três anos (sua última apresentação, ao vivo, foi em dezembro de 1985, em São Caetano do Sul, São Paulo), aceitou o convite. Na capital baiana,iniciaram juntos uma série de 50 shows, que visitou os quatro cantos do Brasil. Uma aventura que acabou resultando no disco A Panela do Diabo, lançado dois dias antes do falecimento de Raul.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Segunda-feira, 21 de agosto de 1989, nove horas da manhã. Dalva Borges da Silva, a empregada de Raul, chegou ao apartamento número 1003, do Edifício Aliança, Zona Central de São Paulo, e encontrou Raul Seixas morto em sua cama. Dalva imediatamente entrou em contato com o médico e a família de Raul. A notícia se espalhou e logo as emissoras de rádio e TV divulgaram o fato.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Fãs, jornalistas e amigos dirigiram-se ao prédio onde Raul residia. Raulzito havia falecido duas horas antes da chegada de Dalva ao prédio, de parada cardíaca, causada pela pancreatite de que sofria há dez anos.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>O corpo foi levado para o Palácio das Convenções do Anhembi, Zona Norte de São Paulo, onde foi velado durante toda a noite e madrugada a dentro. Às oito horas da manhã do dia seguinte o corpo seguiu num jatinho para Salvador, onde foi sepultado às 17 horas no Cemitério Jardim da Saudade.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Passados tantos anos de sua grande viagem, Raul Seixas continua mais vivo do que nunca. Desde seu falecimento em 21 de agosto de 1989, o número de pessoas interessadas em sua vida e obra vem aumentando consideravelmente. Pessoas de todas as faixas etárias e classes sociais se organizam nos inúmeros fãs-clubes criados para homenageá-lo. Casas culturais, praças, ruas, parques e viadutos recebem seu nome.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>Revistas, pôsteres e cerca de 20 livros enfocando sua vida e obra continuam no mercado. Todos os títulos de sua imensa discografia já foram reeditados em CD, e novos títulos são lançados constantemente. Programas de rádio e TV, romarias ao Cemitério Jardim da Saudade, em Salvador, passeatas, carreatas e inúmeros eventos acontecem anualmente em todo o Brasil nas datas de nascimento e morte, 28 de junho e 21 de agosto, respectivamente.</Text>
            <Text style={{ textAlign: 'justify', color: 'white' }}>É por esses e por inúmeros outros motivos que decididamente Raul Seixas está e continuará vivo.</Text>
            <Text style={{ textAlign: 'center', color: 'white', paddingTop: 30, paddingBottom: 20 }}>Sylvio Passos</Text>
          </View>
        </ScrollView>
        <View style={{ bottom: 0 }}>
          <Admob />
        </View>
      </View>
    );
  }
}

